<a href="https://colab.research.google.com/github/Manan1811/Natural-Language-Processing/blob/master/NLP/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from keras.preprocessing.text import one_hot

docs= ['glass of orange Juice',
       'bottle of mango juice',
       'glass of mango shake',
       'drink bottle of banana shake',
       'I want a glass of cold water',
       'The king and the queen', 
       'man and woman']


In [4]:
vocab_size=10000
encoded_docs= [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[3863, 7219, 147, 1844], [4602, 7219, 9257, 1844], [3863, 7219, 9257, 7961], [6419, 4602, 7219, 1370, 7961], [3985, 2498, 7157, 3863, 7219, 7983, 7634], [571, 7967, 7985, 571, 2658], [7253, 7985, 8641]]


## Word Embedding

In [8]:
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding
import numpy as np

embedding_len= 5
max_doc_len=10 # total columns in the embedding matrix we want 
encoded_docs= pad_sequences(encoded_docs, truncating='post', padding='post', maxlen=max_doc_len) # zeros are padded "post" in the embedding matrix
encoded_docs

array([[3863, 7219,  147, 1844,    0,    0,    0,    0,    0,    0],
       [4602, 7219, 9257, 1844,    0,    0,    0,    0,    0,    0],
       [3863, 7219, 9257, 7961,    0,    0,    0,    0,    0,    0],
       [6419, 4602, 7219, 1370, 7961,    0,    0,    0,    0,    0],
       [3985, 2498, 7157, 3863, 7219, 7983, 7634,    0,    0,    0],
       [ 571, 7967, 7985,  571, 2658,    0,    0,    0,    0,    0],
       [7253, 7985, 8641,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [9]:
model= Sequential()
model.add(Embedding(vocab_size, embedding_len, input_length=max_doc_len))
model.compile('rmsprop', 'mse')
output= model.predict(encoded_docs)
output

array([[[-6.6420212e-03, -3.5229862e-02,  3.9639030e-02,  1.8851828e-02,
          4.3684468e-03],
        [-3.1541966e-02,  2.3002412e-02, -3.9213944e-02, -7.6375492e-03,
          3.4958098e-02],
        [ 1.8718805e-02, -1.5767775e-02, -4.1565239e-02, -2.2267247e-02,
         -5.7167038e-03],
        [-8.2029812e-03, -3.6652505e-02, -6.0226917e-03,  2.2156749e-02,
         -1.5452720e-02],
        [-5.3564906e-03,  2.3317207e-02, -2.9470934e-02, -3.6641490e-02,
          3.7120294e-02],
        [-5.3564906e-03,  2.3317207e-02, -2.9470934e-02, -3.6641490e-02,
          3.7120294e-02],
        [-5.3564906e-03,  2.3317207e-02, -2.9470934e-02, -3.6641490e-02,
          3.7120294e-02],
        [-5.3564906e-03,  2.3317207e-02, -2.9470934e-02, -3.6641490e-02,
          3.7120294e-02],
        [-5.3564906e-03,  2.3317207e-02, -2.9470934e-02, -3.6641490e-02,
          3.7120294e-02],
        [-5.3564906e-03,  2.3317207e-02, -2.9470934e-02, -3.6641490e-02,
          3.7120294e-02]],

       [

In [10]:
output[0] # embedding for first line - 'glass of orange juice'
#the last 6 rows are same because the zero padded in the embedding sequence.(10-4==6 || embedding col - no. of words in the line of one-hot = zeros padded)

array([[-0.00664202, -0.03522986,  0.03963903,  0.01885183,  0.00436845],
       [-0.03154197,  0.02300241, -0.03921394, -0.00763755,  0.0349581 ],
       [ 0.01871881, -0.01576778, -0.04156524, -0.02226725, -0.0057167 ],
       [-0.00820298, -0.03665251, -0.00602269,  0.02215675, -0.01545272],
       [-0.00535649,  0.02331721, -0.02947093, -0.03664149,  0.03712029],
       [-0.00535649,  0.02331721, -0.02947093, -0.03664149,  0.03712029],
       [-0.00535649,  0.02331721, -0.02947093, -0.03664149,  0.03712029],
       [-0.00535649,  0.02331721, -0.02947093, -0.03664149,  0.03712029],
       [-0.00535649,  0.02331721, -0.02947093, -0.03664149,  0.03712029],
       [-0.00535649,  0.02331721, -0.02947093, -0.03664149,  0.03712029]],
      dtype=float32)

In [12]:
output[0][0] # embedding for word 'glass'

array([-0.00664202, -0.03522986,  0.03963903,  0.01885183,  0.00436845],
      dtype=float32)